services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATASOURCE_HOST=host.docker.internal:3307
      - DATASOURCE_USER=root
      - DATASOURCE_PASSWORD=root
      - DATASOURCE_DB=tfg
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATA_SOURCE_URL=jdbc:mysql://host.docker.internal:3307/tfg?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=TRUE
    networks:
      - app-network       

  frontend:
      build: ./frontend
      ports:
        - "80:80"
      depends_on:
        - backend
      networks:
        - app-network

  db:
    image: mysql:8.0.35
    environment:
      - MYSQL_DATABASE=tfg
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
